### ISSUE TITLE
har2case AttributeError

### ISSUE THREAD

**Issue by sirfengyu** [HttpRunner/har2case#1]
```
yudeMacBook-Pro:Downloads yufeng$ har2case -V
0.0.6
yudeMacBook-Pro:Downloads yufeng$ har2case Untitled.har a.yaml
Traceback (most recent call last):
  File "/usr/local/bin/har2case", line 11, in <module>
    load_entry_point('har2case==0.0.6', 'console_scripts', 'har2case')()
  File "/usr/local/lib/python3.6/site-packages/har2case-0.0.6-py3.6.egg/har2case/cli.py", line 60, in main
    har_parser = HarParser(har_source_file, args.filter, args.exclude)
  File "/usr/local/lib/python3.6/site-packages/har2case-0.0.6-py3.6.egg/har2case/core.py", line 64, in __init__
    self.testset = self.make_testset()
  File "/usr/local/lib/python3.6/site-packages/har2case-0.0.6-py3.6.egg/har2case/core.py", line 289, in make_testset
    testset = self.make_testcases()
  File "/usr/local/lib/python3.6/site-packages/har2case-0.0.6-py3.6.egg/har2case/core.py", line 268, in make_testcases
    {"test": self.make_testcase(entry_json)}
  File "/usr/local/lib/python3.6/site-packages/har2case-0.0.6-py3.6.egg/har2case/core.py", line 250, in make_testcase
    self._make_request_data(testcase_dict, entry_json)
  File "/usr/local/lib/python3.6/site-packages/har2case-0.0.6-py3.6.egg/har2case/core.py", line 164, in _make_request_data
    if mimeType.startswith("application/json"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by sirfengyu** [comment]
[Untitled.har.txt](https://github.com/HttpRunner/har2case/files/1474231/Untitled.har.txt)
file maybe rename Untitled.har

**Comment by debugtalk** [comment]
@sirfengyu Thanks for your feedback. Fixed.
