### ISSUE TITLE
我用charles把报文导出为har文件，使用命令行转换文件报错

### ISSUE THREAD

**Issue by shichaowei** [HttpRunner/har2case#3]
E:\>har2case 360fengdai.har
Traceback (most recent call last):
  File "C:\Python27\Scripts\har2case-script.py", line 11, in <module>
    load_entry_point('har2case==0.1.1', 'console_scripts', 'har2case')()
  File "C:\Python27\lib\site-packages\har2case-0.1.1-py2.7.egg\har2case\cli.py", line 60, in main
    har_parser = HarParser(har_source_file, args.filter, args.exclude)
  File "C:\Python27\lib\site-packages\har2case-0.1.1-py2.7.egg\har2case\core.py", line 36, in __init__
    self.testset = self.make_testset()
  File "C:\Python27\lib\site-packages\har2case-0.1.1-py2.7.egg\har2case\core.py", line 302, in make_testset
    testset = self.make_testcases()
  File "C:\Python27\lib\site-packages\har2case-0.1.1-py2.7.egg\har2case\core.py", line 281, in make_testcases
    {"test": self.make_testcase(entry_json)}
  File "C:\Python27\lib\site-packages\har2case-0.1.1-py2.7.egg\har2case\core.py", line 264, in make_testcase
    self._make_validate(testcase_dict, entry_json)
  File "C:\Python27\lib\site-packages\har2case-0.1.1-py2.7.egg\har2case\core.py", line 229, in _make_validate
    for key, value in resp_content_json.items():
AttributeError: 'list' object has no attribute 'items'

[360fengdai.zip](https://github.com/HttpRunner/har2case/files/1484435/360fengdai.zip)

**Comment by debugtalk** [comment]
看了下数据，`mimeType`为`json`，但是`text`经过`base64`解码后格式为：

```
[
    {},
    {},
    {}
]
```

```json
"content": {
    "size": 25359,
    "compression": 22175,
    "mimeType": "application/json",
    "text": "W3siaWQiOiI2MENFNjlCN0U0Mjk0NkI0QjRCMzhCQjk1Mjc3RTND......",
    "encoding": "base64"
}
```
